#- platform: mqtt
#  name: Loungeroom Aircon
#  # send_if_off: false
#  initial: 22
#  modes:
#    - "off"
#    - auto
#    - cool
#    - heat
#    - dry
#  swing_modes:
#    - static
#    - swing
#  fan_modes:
#    - auto
#    - quiet
#    - low
#    - medium
#    - high
#  power_command_topic: "lounge/air/power"
#  payload_on: "on"
#  payload_off: "off"
#  mode_command_topic: "lounge/air/mode"
#  temperature_command_topic: "lounge/air/temp"
#  current_temperature_topic: "lounge/stats/temperature"
#  fan_mode_command_topic: "lounge/air/fan"
#  swing_mode_command_topic: "lounge/air/swing"
#  min_temp: 18
#  max_temp: 30
#
#  - platform: mqtt
#    name: Office Aircon
#    # send_if_off: false
#    initial: 24
#    modes:
#      - "off"
#      - auto
#      - cool
#      - heat
#      - dry
#    swing_modes:
#      - static
#      - swing
#    fan_modes:
#      - auto
#      - quiet
#      - low
#      - medium
#      - high
#    power_command_topic: "office/air/power"
#    payload_on: "on"
#    payload_off: "off"
#    mode_command_topic: "office/air/mode"
#    temperature_command_topic: "office/air/temp"
#    current_temperature_topic: "office/stats/temperature"
#    fan_mode_command_topic: "office/air/fan"
#    swing_mode_command_topic: "office/air/swing"
#    min_temp: 18
#    max_temp: 30

- platform: tasmota_irhvac
  name: "Bedroom Aircon"
  command_topic: "cmnd/bedroom/irhvac"
  # Pick one of the following:
  # State is updated when the tasmota device receives an IR signal (includes own transmission and original remote)
  # useful when a normal remote is in use alongside the tasmota device, may be less reliable than the second option.
  #state_topic: "tele/bedroom/RESULT"
  # State is updated when the tasmota device completes IR transmissionm, should be pretty reliable.
  state_topic: "stat/bedroom/RESULT"
  temperature_sensor: sensor.bedroom_temperature
  vendor: "FUJITSU_AC"
  min_temp: 18 #optional - default 16 int value
  max_temp: 28 #optional - default 32 int value
  target_temp: 23 #optional - default 26 int value
  #initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
  away_temp: 24 #optional - default 24 int value
  precision: 0.5 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
  supported_modes:
    - "heat"
    - "cool"
    - "dry"
   # - "fan_only"
    - "auto"
    - "off" #Turns the AC off - Should be in quotes
    # Some devices have "auto" and "fan_only" switched
    # If the following two lines are uncommented, "auto" and "fan" shoud be commented out
    #- auto_fan_only #if remote shows fan but tasmota says auto
    #- fan_only_auto #if remote shows auto but tasmota says fan
  supported_fan_speeds:
    # Some devices say max,but it is high, and auto which is max
    # If you uncomment the following two, you have to comment high and max
    # - auto_max #woud become max
    # - max_high #would become high
    #- on
    #- off
    - low
    - "medium"
    - "high"
    #- middle
    #- focus
    #- diffuse
    #- "min"
    #- "max"
    - auto
  supported_swing_list:
    - "off"
    - "vertical" #up to down
    #- horizontal # Left to right
    #- both
  default_quiet_mode: "Off" #optional - default "Off" string value
  default_turbo_mode: "Off" #optional - default "Off" string value
  default_econo_mode: "Off" #optional - default "Off" string value
  hvac_model: "1" #optional - default "1" string value
  celsius_mode: "On" #optional - default "On" string value
  default_light_mode: "Off" #optional - default "Off" string value
  default_filter_mode: "Off" #optional - default "Off" string value
  default_clean_mode: "Off" #optional - default "Off" string value
  default_beep_mode: "On" #optional - default "Off" string value
  default_sleep_mode: "-1" #optional - default "-1" string value
  
- platform: tasmota_irhvac
  name: "Theatre Aircon"
  command_topic: "cmnd/theatre/irhvac"
  # Pick one of the following:
  # State is updated when the tasmota device receives an IR signal (includes own transmission and original remote)
  # useful when a normal remote is in use alongside the tasmota device, may be less reliable than the second option.
  #state_topic: "tele/bedroom/RESULT"
  # State is updated when the tasmota device completes IR transmissionm, should be pretty reliable.
  state_topic: "stat/theatre/RESULT"
  temperature_sensor: sensor.theatre_temperature
  vendor: "FUJITSU_AC"
  min_temp: 18 #optional - default 16 int value
  max_temp: 28 #optional - default 32 int value
  target_temp: 23 #optional - default 26 int value
  #initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
  away_temp: 24 #optional - default 24 int value
  precision: 1 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
  supported_modes:
    - "heat"
    - "cool"
    - "dry"
   # - "fan_only"
    - "auto"
    - "off" #Turns the AC off - Should be in quotes
    # Some devices have "auto" and "fan_only" switched
    # If the following two lines are uncommented, "auto" and "fan" shoud be commented out
    #- auto_fan_only #if remote shows fan but tasmota says auto
    #- fan_only_auto #if remote shows auto but tasmota says fan
  supported_fan_speeds:
    # Some devices say max,but it is high, and auto which is max
    # If you uncomment the following two, you have to comment high and max
    # - auto_max #woud become max
    # - max_high #would become high
    #- on
    #- off
    - low
    - "medium"
    - "high"
    #- middle
    #- focus
    #- diffuse
    #- "min"
    #- "max"
    - auto
  supported_swing_list:
    - "off"
    - "vertical" #up to down
    #- horizontal # Left to right
    #- both
  default_quiet_mode: "Off" #optional - default "Off" string value
  default_turbo_mode: "Off" #optional - default "Off" string value
  default_econo_mode: "Off" #optional - default "Off" string value
  hvac_model: "1" #optional - default "1" string value
  celsius_mode: "On" #optional - default "On" string value
  default_light_mode: "Off" #optional - default "Off" string value
  default_filter_mode: "Off" #optional - default "Off" string value
  default_clean_mode: "Off" #optional - default "Off" string value
  default_beep_mode: "On" #optional - default "Off" string value
  default_sleep_mode: "-1" #optional - default "-1" string value

#- platform: tasmota_irhvac
#  name: "Loungeroom Aircon 2"
#  command_topic: "cmnd/loungeroom/irhvac"
#  # Pick one of the following:
#  # State is updated when the tasmota device receives an IR signal (includes own transmission and original remote)
#  # useful when a normal remote is in use alongside the tasmota device, may be less reliable than the second option.
#  #state_topic: "tele/bedroom/RESULT"
#  # State is updated when the tasmota device completes IR transmissionm, should be pretty reliable.
#  state_topic: "stat/loungeroom/RESULT"
#  temperature_sensor: sensor.loungeroom_temperature
#  vendor: "FUJITSU_AC"
#  min_temp: 18 #optional - default 16 int value
#  max_temp: 28 #optional - default 32 int value
#  target_temp: 23 #optional - default 26 int value
#  #initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
#  away_temp: 24 #optional - default 24 int value
#  precision: 0.5 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
#  supported_modes:
#    - "heat"
#    - "cool"
#    - "dry"
#   # - "fan_only"
#    - "auto"
#    - "off" #Turns the AC off - Should be in quotes
#    # Some devices have "auto" and "fan_only" switched
#    # If the following two lines are uncommented, "auto" and "fan" shoud be commented out
#    #- auto_fan_only #if remote shows fan but tasmota says auto
#    #- fan_only_auto #if remote shows auto but tasmota says fan
#  supported_fan_speeds:
#    # Some devices say max,but it is high, and auto which is max
#    # If you uncomment the following two, you have to comment high and max
#    # - auto_max #woud become max
#    # - max_high #would become high
#    #- on
#    #- off
#    - low
#    - "medium"
#    - "high"
#    #- middle
#    #- focus
#    #- diffuse
#    #- "min"
#    #- "max"
#    - auto
#  supported_swing_list:
#    - "off"
#    - "vertical" #up to down
#    - horizontal # Left to right
#    - both
#  default_quiet_mode: "Off" #optional - default "Off" string value
#  default_turbo_mode: "Off" #optional - default "Off" string value
#  default_econo_mode: "Off" #optional - default "Off" string value
#  hvac_model: "1" #optional - default "1" string value
#  celsius_mode: "On" #optional - default "On" string value
#  default_light_mode: "Off" #optional - default "Off" string value
#  default_filter_mode: "Off" #optional - default "Off" string value
#  default_clean_mode: "Off" #optional - default "Off" string value
#  default_beep_mode: "On" #optional - default "Off" string value
#  default_sleep_mode: "-1" #optional - default "-1" string value

- platform: smartir
  name: Lounge AC 2
  unique_id: office_ac_2
  device_code: 1294 #1281 #1287
  controller_data: remote.lounge_broadlink_remote_remote
  temperature_sensor: sensor.loungeroom_temperature
  #humidity_sensor: sensor.loungeroom_humidity
  #power_sensor: binary_sensor.ac_power