homeassistant:
  # Name of the location where Home Assistant is running
  name: Venus Residence
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 21
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Brisbane
  # include Customize
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    icon: mdi:home
    radius: 200

  - name: SCUH
    latitude: -26.74760336442635
    longitude: 153.11310311071207
    icon: mdi:briefcase
    radius: 400

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

config:

automation: !include_dir_merge_list automation/

scene: !include scenes.yaml

map:

# upnp:
# port_mapping: false

http:
  # Uncomment this to add a password (recommended!)
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret server_ip

panel_custom:
  - name: ZHA
    sidebar_title: ZHA
    sidebar_icon: mdi:lan
    js_url: /api/hassio/app/entrypoint.js
    url_path: 'config/zha/visualization?config_entry=e13282db2694834610bda980c8a67a97config/server_control'
    embed_iframe: true
    config:
      ingress: core_configurator    
    require_admin: true


lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
#    - url: /hacsfiles/bom-weather-card/bom-weather-card.js
#      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module   
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module       
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module   
    - url: /hacsfiles/zha-network-card/zha-network-card.js
      type: module        
  
# Checks for available updates
#updater:
#  include_used_components: true

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation
      - graph
    entities:
      - sensor.server_uptime
     #- sensor.date
     #- sensor.date_time
     #- sensor.time
     #- sensor.time_date
     #- sensor.time_utc
# View all events in a logbook
logbook:

# Track the sun
sun:

hacs:
  token: !secret hacs_token

recorder:
  db_url: !secret db_url
  purge_keep_days: 31

mobile_app:

ios:
  push:
    categories:
      - name: Garage
        identifier: 'garage'
        actions:
          - identifier: 'CLOSE_GARAGE'
            title: 'Close Garage'
            destructive: true
            authenticationRequired: true
          - identifier: 'DO_NOTHING'
            title: 'Do Nothing'
      - name: sprinkleroff
        identifier: 'sprinkleroff'
        actions:
          - identifier: 'SPRINKLER_OFF'
            title: 'Turn off Sprinkler'
            destructive: true
            authenticationRequired: false
          - identifier: 'DO_NOTHING'
            title: 'Do Nothing'            

mqtt:
  broker: server
  discovery: true

system_health:

notify:
  - name: 'chicane_pushbullet'
    platform: 'pushbullet'
    api_key: !secret pb_apikey

#hue:
#  bridges:
#    - host: !secret hue_host
#      allow_unreachable: true
#      allow_hue_groups: true

binary_sensor:
  - platform: workday
    country: AU
    province: QLD
      

# binary_sensor:
#  - platform: huesensor

# xiaomi_aqara:
  # discovery_retry: 5
  # gateways:
    # - key: !secret xiaomi_key
      # host: !secret xiaomi_ip

#vacuum:
#  - platform: xiaomi_miio
#    host: !secret xiaomi_vacuum_host
#    token: !secret xiaomi_vacuum_token

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points   
    colors: 
      color_path: [255, 255, 255]    

# Text to speech
tts:
  platform: google_translate
  base_url: !secret base_url

logger:
  default: error
  #logs:
    #homeassistant.core: debug
    #homeassistant.components.zha: debug
    #bellows.zigbee.application: debug
    #bellows.ezsp: debug
    #zigpy: debug
    #zigpy_deconz.zigbee.application: debug
    #zigpy_deconz.api: debug
    #zigpy_xbee.zigbee.application: debug
    #zigpy_xbee.api: debug
    #zigpy_zigate: debug
    #zigpy_znp: debug
    #zhaquirks: debug
    #homeassistant.components.http.ban: warning
    # homeassistant.components.miio_gateway: debug
    # homeassistant.components.media_player: warning
    # homeassistant.components.sensor.sensor.bom_sunshine_coast_air_temp_c: debug
    # homeassistant.components.bom: debug
    # homeassistant.components.shell_command.chicane_sleep: debug
    # homeassistant.components.switch.dannys_pc: debug
    #homeassistant.components.homekit: debug
    #custom_components.xiaomi_miot_raw: debug
    #miio: debug
    #pyhap: debug

sensor: !include sensor.yaml

#remote:
#  - platform: harmony
#    name: Living Room
#    host: !secret harmony_ip
#    activity: Watch TV

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

#media_player:
#  - platform: androidtv
#    name: Fire TV
#    host: x.x.x.x
#    adb_server_ip: 127.0.0.1
#    adbkey: '/config/config/android/adbkey'
#    device_class: firetv

shell_command:
  chicane_sleep: 'touch /config/config/sleepchicane.txt'

#apple_tv:

lifx:
  light:

light: !include light.yaml

switch: !include switch.yaml

script: !include script.yaml

climate: !include climate.yaml

group: !include groups.yaml

fan: !include fan.yaml

#circadian_lighting:

adaptive_lighting:
  - name: "Loungeroom"
    lights: 
      - light.loungeroom_1
      - light.loungeroom_2
      - light.loungeroom_3
      - light.loungeroom_4
    min_brightness: 20
  - name: "Kitchen"
    lights: 
      - light.kitchen_1
      - light.kitchen_2  
    min_brightness: 20
  - name: "Bedroom"
    lights: 
     # - light.bedroom_3
     # - light.bedroom_1 
     # - light.bedroom_4 
     # - light.bedroom_2 
     - light.bedroom
    min_brightness: 20
  - name: "Hallway"
    lights: 
      - light.hallway_1
      - light.hallway_2
    min_brightness: 20   

cover:
  - platform: mqtt
    name: 'Garage Door'
    command_topic: "garage/trigger"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    state_topic: "garage/stats/position"

#camera:
  #- platform: bom
  #  name: 'BOM Radar'
  # location: Brisbane

tplink:
  switch:
    - host: !secret tplink_1
    - host: !secret tplink_2

#garbage_collection:
#  sensors:
#    - name: Normal Bin
#      frequency: "weekly"
#      collection_days: wed
#      verbose_state: true
  #  - name: Recycling Bin broken
  #    frequency: "odd-weeks"
  #    collection_days: wed
  #    verbose_state: true

#    - name: Recycling Bin 
#      frequency: "every-n-days"
#      first_date: '2020-12-30'
#      period: 14
#      #collection_days: wed
#      verbose_state: true

input_boolean:
  dannyhome:
    icon: mdi:home
    name: Danny Home Status

  lizhome:
    icon: mdi:home
    name: Liz Home Status

  danny_bin_alerted:
    icon: mdi:home
    name: Danny Bin Alerted

  liz_bin_alerted:
    icon: mdi:home
    name: Liz Bin Alerted

  both_bin_alerted:
    icon: mdi:home
    name: Both Bin Alerted

  on_holidays:
    icon: mdi:beach
    name: On Holidays

  bedtime_triggered:
    icon: mdi:hotel
    name: Bedtime Triggered

  outside_triggered:
    name: Outside Triggered

input_number:
  heater_on_below_temp:
    name: "Heater On Below"
    min: 16
    max: 24
    step: 0.5
    unit_of_measurement: "°C"
    icon: mdi:snowman

  heater_off_above_temp:
    name: "Heater Off Above"
    min: 20
    max: 26
    step: 0.5
    unit_of_measurement: "°C"
    icon: mdi:hot-tub

  test_num:
    name: "test num"
    min: 0
    max: 255

  weather_pws_precip_month:
    name: Monthly Rainfall
    min: 0
    max: 600
    unit_of_measurement: "mm"
    step: 0.01


google_assistant:
  project_id: hass-cc443
  service_account: !include HASS-66445e08203e.json
  expose_by_default: false
  entity_config:
    switch.back_sprinkler:
      name: Back Sprinkler
      expose: true
      room: Outside

    switch.mozzie_zapper:
      name: Mozzie Zapper
      expose: true
      room: Kitchen
    switch.coffee_machine:
      name: Coffee Machine
      expose: true
      room: Kitchen
    climate.loungeroom_aircon:
      name: Loungeroom Aircon
      expose: true
      room: Lounge Room
    climate.gym_aircon:
      name: Gym Aircon
      expose: true
      room: Gym
    # cover.garage_door:
    #  name: Garage Door
    #  expose: true
    #  room: Garage
    # switch.living_room_harmony_watch_tv:
    #  name: Lounge TV
    #  expose: true
    #  room: Lounge Room
    switch.cooking_light:
      name: Cooking Light
      expose: true
      room: Cooking
    light.loungeroom:
      name: Loungeroom Light
      expose: true
      room: Lounge Room
    light.kitchen:
      name: Kitchen Light
      expose: true
      room: Kitchen
    light.dining_room:
      name: Dining Light
      expose: true
      room: Dining Room
    light.gym:
      name: Gym Light
      expose: true
      room: Gym
    light.niche:
      name: Niche Light
      expose: true
      room: Niche
    light.bedroom:
      name: Bedroom Light
      expose: true
      room: Bedroom      
    light.outside:
      name: Outside Light
      expose: true
      room: Outside
    scene.goodnight_scene:
      name: Goodnight
      expose: true
    scene.bedtime_scene:
      name: Bed Time
      expose: true
    scene.gaming_time:
      name: Gaming Time
      expose: true
    script.bedroom_circadian:
      name: Bedroom Circadian
      expose: true 
    script.hallway_circadian:
      name: Hallway Circadian
      expose: true  
    script.kitchen_circadian:
      name: Kitchen Circadian
      expose: true  
    script.loungeroom_circadian:
      name: Loungeroom Circadian
      expose: true  
      # light.pantry:
      #   name: Pantry Light
      #   expose: true
      #   room: Pantry

homekit:
  #auto_start: false
  entity_config:
    sensor.outside_temperature:
      name: Outside Temperature
    sensor.outside_humidity:
      name: Outside Humidity
    binary_sensor.door_outside_rear:
      name: Outside Door
    switch.mozzie_zapper:
      type: outlet
    switch.cooking_light:
      type: outlet
    light.dining_room:
      name: Dining Rooms Lights
    light.pantry:
      name: Pantry Light
    scene.bedtime_scene:
      name: Bedtime Scene Switch
    scene.gaming_time:
      name: Gaming Time Scene Switch


  filter:
    exclude_domains:
      - automation
      - device_tracker
      - light
      - remote
      - binary_sensor
      - media_player
      - sensor
      - switch
      - vacuum
    exclude_entities:
      #- climate.office_aircon
      - input_boolean.danny_bin_alerted
      - input_boolean.liz_bin_alerted
      - input_boolean.both_bin_alerted
      - script.harm_living_turn_off
      - script.harm_living_watch_apple_tv
      - script.harm_living_watch_tv
      - script.harm_living_watch_smart_tv
      - script.restart_hass
#      - camera.bom_radar
      - switch.adaptive_lighting_adapt_brightness_bedroom
      - switch.adaptive_lighting_adapt_brightness_hallway
      - switch.adaptive_lighting_adapt_brightness_kitchen
      - switch.adaptive_lighting_adapt_brightness_loungeroom
      - switch.adaptive_lighting_adapt_color_bedroom
      - switch.adaptive_lighting_adapt_color_hallway
      - switch.adaptive_lighting_adapt_color_kitchen
      - switch.adaptive_lighting_adapt_color_loungeroom
      - switch.adaptive_lighting_bedroom
      - switch.adaptive_lighting_hallway
      - switch.adaptive_lighting_kitchen
      - switch.adaptive_lighting_loungeroom
      - switch.adaptive_lighting_sleep_mode_bedroom
      - switch.adaptive_lighting_sleep_mode_hallway
      - switch.adaptive_lighting_sleep_mode_kitchen
      - switch.adaptive_lighting_sleep_mode_loungeroom
      - input_boolean.outside_triggered
      - camera.xiaomi_cloud_map_extractor
      #- script.roborock_clean_east_wing
      #- script.roborock_clean_ensuite
      #- script.roborock_clean_hallway
      #- script.roborock_clean_kitchen
      #- script.roborock_clean_laundry
      #- script.roborock_clean_master
      #- script.roborock_clean_office
      #- script.roborock_clean_server_room
      #- script.roborock_clean_west_wing
      #- script.office_air_fan_low
      #- script.bedroom_air_fan_low

    include_entities:
      #- switch.bedroom_heater
      - switch.coffee_machine
      - switch.cooking_light
      - switch.danny_s_pc
      - switch.mozzie_zapper
      - switch.back_sprinkler
      - light.bathroom
      - light.loungeroom_1
      - light.loungeroom_2
      - light.loungeroom_3
      - light.loungeroom_4
      - light.kitchen_1
      - light.kitchen_2
      - light.outside
      - light.gym
      - light.niche
      - light.dining_room
      - light.garage
      - light.wardrobe
      - light.pantry_1
      - light.bedroom_1
      - light.bedroom_2
      - light.bedroom_3
      - light.bedroom_4
      - light.hallway_1
      - light.hallway_2
      - sensor.garage_temperature
      - sensor.gym_temperature
      - sensor.bedroom_temperature
      - sensor.loungeroom_temperature
      - sensor.outside_temperature
      - sensor.pantry_temperature
      - sensor.garage_humidity
      - sensor.gym_humidity
      - sensor.bedroom_humidity
      - sensor.loungeroom_humidity
      - sensor.outside_humidity
      - sensor.pantry_humidity    

#miio_gateway:
#  host: 10.0.0.164    # IP of your gateway
#  port: 54321          # port running miio_client, defaults to 54321
#  sensors:
#    - sid: lumi.158d0005224e27
#      class: door                           # motion sensor
#      friendly_name: Office Door Sensor  # display name (optional)
#    - sid: lumi.158d00052245a5
#      class: door 
#      friendly_name: Front Door Sensor  # display name (optional)


