broker: server
discovery: true

sensor:
  - name: "Pantry Temperature"
    state_topic: "tele/pantry/SENSOR"
    value_template: "{{ value_json['AM2301'].Temperature }}"
    availability_topic: "tele/pantry/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"
 
  - name: "Pantry Humidity"
    state_topic: "tele/pantry/SENSOR"
    value_template: "{{ value_json['AM2301'].Humidity }}"
    availability_topic: "tele/pantry/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Loungeroom Temperature"
    state_topic: "tele/loungeroom/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/loungeroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Loungeroom Humidity"
    state_topic: "tele/loungeroom/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/loungeroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Loungeroom Pressure"
    state_topic: "tele/loungeroom/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/loungeroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: pressure
    unit_of_measurement: "hPa"

  - name: "Gym Temperature"
    state_topic: "tele/gym/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/gym/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Gym Humidity"
    state_topic: "tele/gym/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/gym/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Gym Pressure"
    state_topic: "tele/gym/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/gym/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "hPa"
    device_class: pressure

  - name: "Bedroom Temperature"
    state_topic: "tele/bedroom/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/bedroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Bedroom Humidity"
    state_topic: "tele/bedroom/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/bedroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Bedroom Pressure"
    state_topic: "tele/bedroom/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/bedroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "hPa"
    device_class: pressure

  - name: "Outside Temperature"
    state_topic: "tele/outside_temp/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/outside_temp/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Outside Pressure"
    state_topic: "tele/outside_temp/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/outside_temp/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "hPa"
    device_class: pressure

  - name: "Outside Humidity"
    state_topic: "tele/outside_temp/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/outside_temp/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Office Temperature"
    state_topic: "tele/office/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/office/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Office Pressure"
    state_topic: "tele/office/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/office/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "hPa"
    device_class: pressure

  - name: "Office Humidity"
    state_topic: "tele/office/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/office/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Garage Temperature"
    state_topic: "garage/stats/temperature"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Garage Humidity"
    state_topic: "garage/stats/humidity"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Garage Pressure"
    state_topic: "garage/stats/pressure"
    unit_of_measurement: "hPa"