#broker: server
#discovery: true

switch:
  - unique_id: back_sprinker
    name: "Back Sprinkler"
    state_topic: "stat/sprinkler/POWER"
    command_topic: "cmnd/sprinkler/POWER"
    availability_topic : "tele/sprinkler/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"

cover:
  - name: 'Garage Door'
    command_topic: "garage/trigger"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    state_topic: "garage/stats/position"

sensor:
  - name: "Pantry Temperature"
    state_topic: "tele/pantry/SENSOR"
    value_template: "{{ value_json['AM2301'].Temperature }}"
    availability_topic: "tele/pantry/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"
 
  - name: "Pantry Humidity"
    state_topic: "tele/pantry/SENSOR"
    value_template: "{{ value_json['AM2301'].Humidity }}"
    availability_topic: "tele/pantry/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

#  - name: "Loungeroom Temperature"
#    unique_id: lounge_temp
#    state_topic: "tele/loungeroom/SENSOR"
#    value_template: "{{ value_json['BME280'].Temperature }}"
#    availability_topic: "tele/loungeroom/LWT"
#    payload_available: "Online"
#    payload_not_available: "Offline"
#    device_class: temperature
#    unit_of_measurement: "°C"
#  - name: "Loungeroom Humidity"
#    unique_id: lounge_hum
#    state_topic: "tele/loungeroom/SENSOR"
#    value_template: "{{ value_json['BME280'].Humidity }}"
#    availability_topic: "tele/loungeroom/LWT"
#    payload_available: "Online"
#    payload_not_available: "Offline"
#    device_class: humidity
#    unit_of_measurement: "%"
#  - name: "Loungeroom Pressure"
#    unique_id: lounge_press
#    state_topic: "tele/loungeroom/SENSOR"
#    value_template: "{{ value_json['BME280'].Pressure }}"
#    availability_topic: "tele/loungeroom/LWT"
#    payload_available: "Online"
#    payload_not_available: "Offline"
#    device_class: pressure
#    unit_of_measurement: "hPa"

  - name: "Gym Temperature"
    state_topic: "tele/gym/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/gym/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Gym Humidity"
    state_topic: "tele/gym/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/gym/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Gym Pressure"
    state_topic: "tele/gym/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/gym/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "hPa"
    device_class: pressure

  - name: "Bedroom Temperature"
    state_topic: "tele/bedroom/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/bedroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Bedroom Humidity"
    state_topic: "tele/bedroom/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/bedroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Bedroom Pressure"
    state_topic: "tele/bedroom/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/bedroom/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "hPa"
    device_class: pressure

  - name: "Outside Temperature"
    state_topic: "tele/outside_temp/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/outside_temp/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Outside Pressure"
    state_topic: "tele/outside_temp/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/outside_temp/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "hPa"
    device_class: pressure

  - name: "Outside Humidity"
    state_topic: "tele/outside_temp/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/outside_temp/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Office Temperature"
    state_topic: "tele/office/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    availability_topic: "tele/office/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Office Pressure"
    state_topic: "tele/office/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure }}"
    availability_topic: "tele/office/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "hPa"
    device_class: pressure

  - name: "Office Humidity"
    state_topic: "tele/office/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    availability_topic: "tele/office/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Garage Temperature"
    state_topic: "garage/stats/temperature"
    device_class: temperature
    unit_of_measurement: "°C"

  - name: "Garage Humidity"
    state_topic: "garage/stats/humidity"
    device_class: humidity
    unit_of_measurement: "%"

  - name: "Garage Pressure"
    state_topic: "garage/stats/pressure"
    unit_of_measurement: "hPa"

light:
  - name: Gym
    command_topic: "gymlights/lights/cmnd/POWER"
    availability_topic: "gymlights/lights/tele/LWT"
    state_topic: "gymlights/lights/tele/STATE"
    state_value_template: "{{ value_json.POWER }}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: Outside Real
    command_topic: "outside/lights/cmnd/POWER"
    availability_topic: "outside/lights/tele/LWT"
    state_topic: "outside/lights/tele/STATE"
    state_value_template: "{{ value_json.POWER }}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - name: Dining Room
    command_topic: "dining/lights/cmnd/POWER1"
    availability_topic: "dining/lights/tele/LWT"
    state_topic: "dining/lights/tele/STATE"
    state_value_template: "{{ value_json.POWER1 }}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: Niche
    command_topic: "dining/lights/cmnd/POWER2"
    availability_topic: "dining/lights/tele/LWT"
    state_topic: "dining/lights/tele/STATE"
    state_value_template: "{{ value_json.POWER2 }}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: Wardrobe
    command_topic: "wardrobe/lights/cmnd/POWER"
    availability_topic: "wardrobe/lights/tele/LWT"
    state_topic: "wardrobe/lights/tele/STATE"
    state_value_template: "{{ value_json.POWER }}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: Garage
    command_topic: "garage_sonoff/lights/cmnd/POWER"
    availability_topic: "garage_sonoff/lights/tele/LWT"
    state_topic: "garage_sonoff/lights/tele/STATE"
    state_value_template: "{{ value_json.POWER }}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"        