####BINS ARRIVE HOME#####
- alias: 'Recyling Bin - Danny Arrives Home'
  trigger:
    platform: state
    entity_id: device_tracker.ichicane
    to: 'home'
    for:
      minutes: 4
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:59:59'
        after: '14:00:00'
      - condition: state
        entity_id: sensor.recycling_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.danny_bin_alerted
        state: 'off'
  action:
    - service: notify.mobile_app_ichicane
      data:
        title: "Recycling Bin Week"
        message: "Recycling Bin Week"
        #target: 'device/iChicane'
    - service: input_boolean.turn_on
      entity_id: input_boolean.danny_bin_alerted

- alias: 'Recyling Bin - Liz Arrives Home'
  trigger:
    platform: state
    entity_id: device_tracker.lizsiphone
    to: 'home'
    for:
      minutes: 4
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:59:59'
        after: '14:00:00'
      - condition: state
        entity_id: sensor.recycling_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.liz_bin_alerted
        state: 'off'
  action:
    - service: notify.mobile_app_duffel
      data:
        title: "Recycling Bin Week"
        message: "Recycling Bin Week"
    - service: input_boolean.turn_on
      entity_id: input_boolean.liz_bin_alerted

- alias: 'Recyling Bin - Both Arrives Home'
  trigger:
    platform: state
    entity_id: group.at_home
    to: 'home'
    for:
      minutes: 4
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:59:59'
        after: '14:00:00'
      - condition: state
        entity_id: sensor.recycling_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.both_bin_alerted
        state: 'off'
  action:
    - service: tts.google_translate_say
      data:
        entity_id: group.google_homes
        message: "Good Afternoon, today is Recycling Bin day"
    - service: input_boolean.turn_on
      entity_id: input_boolean.both_bin_alerted

- alias: 'Green Bin - Danny Arrives Home'
  trigger:
    platform: state
    entity_id: device_tracker.ichicane
    to: 'home'
    for:
      minutes: 4
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:59:59'
        after: '14:00:00'
      - condition: state
        entity_id: sensor.green_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.danny_bin_alerted
        state: 'off'
  action:
    - service: notify.mobile_app_ichicane
      data:
        title: "Green Bin Week"
        message: "Green Bin Week"
        #target: 'device/iChicane'
    - service: input_boolean.turn_on
      entity_id: input_boolean.danny_bin_alerted

- alias: 'Green Bin - Liz Arrives Home'
  trigger:
    platform: state
    entity_id: device_tracker.lizsiphone
    to: 'home'
    for:
      minutes: 4
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:59:59'
        after: '14:00:00'
      - condition: state
        entity_id: sensor.green_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.liz_bin_alerted
        state: 'off'
  action:
    - service: notify.mobile_app_duffel
      data:
        title: "Green Bin Week"
        message: "Green Bin Week"
    - service: input_boolean.turn_on
      entity_id: input_boolean.liz_bin_alerted

- alias: 'Green Bin - Both Arrives Home'
  trigger:
    platform: state
    entity_id: group.at_home
    to: 'home'
    for:
      minutes: 4
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:59:59'
        after: '14:00:00'
      - condition: state
        entity_id: sensor.green_bin_today
        state: 'Today'

      - condition: state
        entity_id: input_boolean.both_bin_alerted
        state: 'off'
  action:
    - service: tts.google_translate_say
      data:
        entity_id: group.google_homes
        message: "Good Afternoon, today is Green Bin day"
    - service: input_boolean.turn_on
      entity_id: input_boolean.both_bin_alerted

###BINS ALREADY HOME###
- alias: 'Recyling Bin - Danny Is Home'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.ichicane
        state: 'home'
      - condition: state
        entity_id: sensor.recycling_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.danny_bin_alerted
        state: 'off'
  action:
    - service: notify.mobile_app_ichicane
      data:
        title: "Recycling Bin Week"
        message: "Recycling Bin Week"
        #target: 'device/iChicane'
    - service: input_boolean.turn_on
      entity_id: input_boolean.danny_bin_alerted

- alias: 'Recyling Bin - Liz Is Home'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.lizsiphone
        state: 'home'
      - condition: state
        entity_id: sensor.recycling_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.liz_bin_alerted
        state: 'off'
  action:
    - service: notify.mobile_app_duffel
      data:
        title: "Recycling Bin Week"
        message: "Recycling Bin Week"
    - service: input_boolean.turn_on
      entity_id: input_boolean.liz_bin_alerted

- alias: 'Recyling Bin - Both Is Home'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.at_home
        state: 'home'
      - condition: state
        entity_id: sensor.recycling_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.both_bin_alerted
        state: 'off'
  action:
    - service: tts.google_translate_say
      data:
        entity_id: group.google_homes
        message: "Good Afternoon, today is Recycling Bin day"
    - service: input_boolean.turn_on
      entity_id: input_boolean.both_bin_alerted

- alias: 'Green Bin - Danny Is Home'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.ichicane
        state: 'home'
      - condition: state
        entity_id: sensor.green_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.danny_bin_alerted
        state: 'off'
  action:
    - service: notify.mobile_app_ichicane
      data:
        title: "Green Bin Week"
        message: "Green Bin Week"
        #target: 'device/iChicane'
    - service: input_boolean.turn_on
      entity_id: input_boolean.danny_bin_alerted

- alias: 'Green Bin - Liz Is Home'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.lizsiphone
        state: 'home'
      - condition: state
        entity_id: sensor.green_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.liz_bin_alerted
        state: 'off'
  action:
    - service: notify.mobile_app_duffel
      data:
        title: "Green Bin Week"
        message: "Green Bin Week"
    - service: input_boolean.turn_on
      entity_id: input_boolean.liz_bin_alerted

- alias: 'Green Bin - Both Is Home'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.at_home
        state: 'home'
      - condition: state
        entity_id: sensor.green_bin_today
        state: 'Today'
      - condition: state
        entity_id: input_boolean.both_bin_alerted
        state: 'off'
  action:
    - service: tts.google_translate_say
      data:
        entity_id: group.google_homes
        message: "Good Afternoon, today is Green Bin day"
    - service: input_boolean.turn_on
      entity_id: input_boolean.both_bin_alerted
