- alias: 'Check Tasmota State on Start'
  id: 'Check Tasmota State on Start'
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mqtt.publish
      data:
        topic: office/lights/cmnd/STATE
        payload: ''
    - service: mqtt.publish
      data:
        topic: outside/lights/cmnd/STATE
        payload: ''
    - service: mqtt.publish
      data:
        topic: dining/lights/cmnd/STATE
        payload: ''
    - service: mqtt.publish
      data:
        topic: cmnd/office/STATUS
        payload: '8'     
    - service: mqtt.publish
      data:
        topic: cmnd/loungeroom/STATUS
        payload: '8'             
    - service: mqtt.publish
      data:
        topic: cmnd/bedroom/STATUS
        payload: '8'    